### ISSUE TITLE
No Display output

### ISSUE THREAD

**Issue by T4KUUY4** [nickshl/SmartPendant#1]
HI, i have your pendant in front of me and i flashed the firmware from the release folder with stm32cube programmer. all went fine but i dont see anything on the screen. 

Right now its connected via UART (RX to TX and vice versa) to a octopus max ez running grblhal

any ideas as to what the problem could be?

**Comment by nickshl** [comment]
Before push, I always upload hex to SmartPendant and to BlackPill. What hardware are you using? Have you make PCBs or have you use discrete modules?

**Comment by jacoschutte** [comment]
Did you solder the 3.3 bridge to power the display ? It is located under
the usb c connector of the black pill. I had the same thing happen to me.
After I soldered this everything worked perfectly

**Comment by nickshl** [comment]
@jacoschutte  you are correct. There selectable voltage to LCD backlight: 3.3V or 5V. According datasheet current trough LEDs backlight should be 120mA and forward voltage is 2.9-3.3V. That is why to use 3.3V probably is not a good idea, I probably will remove it at some point. I used two resistors in parallel: 33 Ohm and 47 Ohm which gives total resistance 19.4 Ohm. This resistance should limit current trough LEDs to 120 mA in worst case scenario: input is 5V(_which slightly less since there diode to prevent reverse polarity_) and forward voltage is 2.9V(_I believe white LEDs has more than that_).

So, LED PWR 5V solder bridge should be soldered to turn on backlight.
Buzzer 5V(_or 3.3V but only one!_) solder bridge should be soldered to make sounds(_not used currently beside Tetris_).
BLE_BTN A0 solder bridge should be soldered to use button on upper edge to gain/release control.
LED MPG and LED VCC solder bridge should be soldered to use LED4 as control request indicator.

**Comment by T4KUUY4** [comment]
Thanks for the quick Response!
Thats what I missed it seems. I thought "LED-power" is refering to the Status led's. 

It might be worth renaming it to LCD-Power.
I will give this a try soon.

Thanks

**Comment by T4KUUY4** [comment]
Thanks yall. This is now solved and its working as intended.

I do have some feedback though regarding documentation etc:
1: Change the layout or the pcb length to eliminate the possibilty for shorting the 3.3V with GND with the dial wheel.
2: Add Documentation as to what the solder bridges do. I for example had no clue that LED_PWR is refering to the backlight. LCD_PWR would have made much more sense.
3: add a printed shim in between the display and the pcb. 

Thanks for that awesome design!
Let me know if you need any help with anything.

~Tom

**Comment by nickshl** [comment]
> 1: Change the layout or the pcb length to eliminate the possibilty for shorting the 3.3V with GND with the dial wheel.

I use two layers of kapton tape on top of those pads. I will remove those pads in next design.

> 2: Add Documentation as to what the solder bridges do. I for example had no clue that LED_PWR is refering to the backlight. LCD_PWR would have made much more sense.

I will remove those solder bridges. LCD_PWR isn't good idea since it is not a LCD power, it is LCD backlight power. And backlight done with LEDs. That is why it called LED_PWR. 

> 3: add a printed shim in between the display and the pcb.

I milled out all protruding pins to be less than 0.7 mm(_thickness of VHB tape_). It wasn't good idea to design board this way. I understand it when tried to assemble 5 units... in next revision I will replace all trough-hole components to SMD ones, it should make assembling way simpler.

**Comment by T4KUUY4** [comment]
@nickshl Thanks for the answer.
One more thing, could you export the CAD model in a step format?
